# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_row_fields import DataRowFields  # noqa: F401,E501
from swagger_server import util


class DataRow(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, fields: List[DataRowFields]=None):  # noqa: E501
        """DataRow - a model defined in Swagger

        :param fields: The fields of this DataRow.  # noqa: E501
        :type fields: List[DataRowFields]
        """
        self.swagger_types = {
            'fields': List[DataRowFields]
        }

        self.attribute_map = {
            'fields': 'fields'
        }
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'DataRow':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataRow of this DataRow.  # noqa: E501
        :rtype: DataRow
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fields(self) -> List[DataRowFields]:
        """Gets the fields of this DataRow.


        :return: The fields of this DataRow.
        :rtype: List[DataRowFields]
        """
        return self._fields

    @fields.setter
    def fields(self, fields: List[DataRowFields]):
        """Sets the fields of this DataRow.


        :param fields: The fields of this DataRow.
        :type fields: List[DataRowFields]
        """

        self._fields = fields
