# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_row import DataRow  # noqa: F401,E501
from swagger_server import util


class DataSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, fields: DataRow=None):  # noqa: E501
        """DataSchema - a model defined in Swagger

        :param id: The id of this DataSchema.  # noqa: E501
        :type id: str
        :param name: The name of this DataSchema.  # noqa: E501
        :type name: str
        :param fields: The fields of this DataSchema.  # noqa: E501
        :type fields: DataRow
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'fields': DataRow
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'fields': 'fields'
        }
        self._id = id
        self._name = name
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'DataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataSchema of this DataSchema.  # noqa: E501
        :rtype: DataSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DataSchema.


        :return: The id of this DataSchema.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DataSchema.


        :param id: The id of this DataSchema.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this DataSchema.


        :return: The name of this DataSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DataSchema.


        :param name: The name of this DataSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def fields(self) -> DataRow:
        """Gets the fields of this DataSchema.


        :return: The fields of this DataSchema.
        :rtype: DataRow
        """
        return self._fields

    @fields.setter
    def fields(self, fields: DataRow):
        """Sets the fields of this DataSchema.


        :param fields: The fields of this DataSchema.
        :type fields: DataRow
        """

        self._fields = fields
