# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataRowFields(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, field: str=None, value: str=None):  # noqa: E501
        """DataRowFields - a model defined in Swagger

        :param field: The field of this DataRowFields.  # noqa: E501
        :type field: str
        :param value: The value of this DataRowFields.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'field': str,
            'value': str
        }

        self.attribute_map = {
            'field': 'field',
            'value': 'value'
        }
        self._field = field
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'DataRowFields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataRow_fields of this DataRowFields.  # noqa: E501
        :rtype: DataRowFields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field(self) -> str:
        """Gets the field of this DataRowFields.


        :return: The field of this DataRowFields.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field: str):
        """Sets the field of this DataRowFields.


        :param field: The field of this DataRowFields.
        :type field: str
        """

        self._field = field

    @property
    def value(self) -> str:
        """Gets the value of this DataRowFields.


        :return: The value of this DataRowFields.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this DataRowFields.


        :param value: The value of this DataRowFields.
        :type value: str
        """

        self._value = value
