# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_row import DataRow  # noqa: F401,E501
from swagger_server import util


class DataData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: DataRow=None):  # noqa: E501
        """DataData - a model defined in Swagger

        :param data: The data of this DataData.  # noqa: E501
        :type data: DataRow
        """
        self.swagger_types = {
            'data': DataRow
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DataData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Data_data of this DataData.  # noqa: E501
        :rtype: DataData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> DataRow:
        """Gets the data of this DataData.


        :return: The data of this DataData.
        :rtype: DataRow
        """
        return self._data

    @data.setter
    def data(self, data: DataRow):
        """Sets the data of this DataData.


        :param data: The data of this DataData.
        :type data: DataRow
        """

        self._data = data
