# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_row import DataRow  # noqa: F401,E501
from swagger_server import util


class ModelSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, prediction: str=None, schema_id: str=None, version: int=None):  # noqa: E501
        """DataSchema - a model defined in Swagger

        :param id: The id of this DataSchema.  # noqa: E501
        :type id: str
        :param name: The name of this DataSchema.  # noqa: E501
        :type name: str
        :param fields: The fields of this DataSchema.  # noqa: E501
        :type fields: DataRow
        """
        self.swagger_types = {
            'id': str,
            'name':str,
            'prediction': str,
            'schema_id':str,
            'version':int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'prediction': 'prediction',
            'schema_id':'schema_id',
            'version':'version'
        }
        self._id = id
        self._name = name
        self._prediction = prediction
        self._schema_id = schema_id
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'DataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataSchema of this DataSchema.  # noqa: E501
        :rtype: DataSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DataSchema.


        :return: The id of this DataSchema.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DataSchema.


        :param id: The id of this DataSchema.
        :type id: str
        """

        self._id= id

    @property
    def name(self) -> str:
        """Gets the id of this DataSchema.


        :return: The id of this DataSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the id of this DataSchema.


        :param id: The id of this DataSchema.
        :type id: str
        """

        self._name= name


    @property
    def prediction(self) -> str:
        """Gets the name of this DataSchema.


        :return: The name of this DataSchema.
        :rtype: str
        """
        return self._prediction

    @prediction.setter
    def prediction(self, prediction: str):
        """Sets the name of this DataSchema.


        :param name: The name of this DataSchema.
        :type name: str
        """

        self._prediction = prediction

    @property
    def schema_id(self) -> str:
        """Gets the name of this DataSchema.


        :return: The name of this DataSchema.
        :rtype: str
        """
        return self._schema_id

    @schema_id.setter
    def schema_id(self, schema_id: str):
        """Sets the name of this DataSchema.


        :param name: The name of this DataSchema.
        :type name: str
        """

        self._schema_id = schema_id


    @property
    def version(self) -> int:
        """Gets the name of this DataSchema.


        :return: The name of this DataSchema.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: int):
        """Sets the name of this DataSchema.


        :param name: The name of this DataSchema.
        :type name: str
        """

        self._version = version