# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SimulationStart(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, scenario_id: str=None, parameters: object=None):  # noqa: E501
        """SimulationStart - a model defined in Swagger

        :param scenario_id: The scenario_id of this SimulationStart.  # noqa: E501
        :type scenario_id: str
        :param parameters: The parameters of this SimulationStart.  # noqa: E501
        :type parameters: object
        """
        self.swagger_types = {
            'scenario_id': str,
            'parameters': object
        }

        self.attribute_map = {
            'scenario_id': 'scenarioId',
            'parameters': 'parameters'
        }
        self._scenario_id = scenario_id
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'SimulationStart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimulationStart of this SimulationStart.  # noqa: E501
        :rtype: SimulationStart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scenario_id(self) -> str:
        """Gets the scenario_id of this SimulationStart.


        :return: The scenario_id of this SimulationStart.
        :rtype: str
        """
        return self._scenario_id

    @scenario_id.setter
    def scenario_id(self, scenario_id: str):
        """Sets the scenario_id of this SimulationStart.


        :param scenario_id: The scenario_id of this SimulationStart.
        :type scenario_id: str
        """

        self._scenario_id = scenario_id

    @property
    def parameters(self) -> object:
        """Gets the parameters of this SimulationStart.


        :return: The parameters of this SimulationStart.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this SimulationStart.


        :param parameters: The parameters of this SimulationStart.
        :type parameters: object
        """

        self._parameters = parameters
