openapi: 3.0.1
info:
  title: Oversale Solicitation API
  description: API Documentation for the oversale solicitation project
  contact:
    email: deahln@rpi.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:3000/api
tags:
- name: Users
  description: User management and authentication
- name: System
  description: System-level api calls for health
- name: Data
  description: Database insertion and management
- name: Model
  description: Machine learning model and analytics
- name: Simulation
  description: Control and status of simulations
- name: Scenario
  description: Defines and controls a scenario
- name: Bid
  description: Endpoints for the prototype interface
paths:
  /ping:
    get:
      tags:
      - System
      summary: Check if system is up and running
      description: Pings the server to check for a healthy response
      operationId: ping_server
      responses:
        "200":
          description: successful ping
          content: {}
      x-swagger-router-controller: swagger_server.controllers.system_controller
      x-openapi-router-controller: swagger_server.controllers.system_controller
  /currentUser:
    get:
      tags:
      - Users
      summary: gets currently authenticated user
      description: Retrieves information about the current user from the microsoft
        Graph API
      operationId: get_users
      responses:
        "200":
          description: list of all users
          content: {}
        "400":
          description: Generic error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-swagger-router-controller: swagger_server.controllers.users_controller
      x-openapi-router-controller: swagger_server.controllers.users_controller
  /schema:
    post:
      tags:
      - Schema
      summary: Add data of scheme type with csv format.
      operationId: post_schema_data
      parameters:
      - name: name
        in: query
        description: name of schema
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              example:
                "cola,colb,colc\ntype1,type2,type3\ndata1,data2,data3\n..."
                
        required: true
        description:
          "First row is column names, second row is data types, remaining are rows of data"
      responses:
        "200":
          description: Rows effected
        "404":
          description: Schema doesnt exist
        "500":
          description: Data is improper
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.schema_controller
    get:
      tags:
      - Data
      - Schema
      summary: Lists all data shemes
      operationId: get_data_schemes
      responses:
        "200":
          description: A list of schemas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSchema'
                x-content-type: application/json
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.schema_controller
  /data:
    summary: Controls the storage, listing, control, and retrieval of data from the
      simulation engine.
    get:
      tags:
      - Data
      summary: Get data of scheme type
      operationId: get_data
      parameters:
      - name: name
        in: query
        description: name of schema
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: amount
        in: query
        description: amount of data
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: filters
        in: query
        description: column specific filters (..:columnname,value)
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Rows Returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataRow'
                x-content-type: application/json
        "404":
          description: No data found
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.data_controller
    put:
      tags:
      - Data
      summary: Add data scheme
      operationId: put_add_scheme
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSchema'
        required: true
      responses:
        "200":
          description: Scheme successfully added.
        "400":
          description: Invalid input
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.data_controller
    post:
      tags:
      - Data
      summary: Add data of scheme type
      operationId: post_add_data
      parameters:
      - name: name
        in: query
        description: name of schema
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
        required: true
      responses:
        "200":
          description: Rows effected
        "404":
          description: Schema doesnt exist
        "500":
          description: Data is improper
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.data_controller
    delete:
      tags:
      - Data
      summary: Delete data of scheme type
      operationId: delete_data
      parameters:
      - name: name
        in: query
        description: name of schema
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Rows effected
          content:
            application/json:
              schema:
                type: integer
                x-content-type: application/json
        "404":
          description: Failure to find schema
        default:
          description: Default error sample response
      security:
      - OAuth2:
        - User.ReadBasic.All
      x-openapi-router-controller: swagger_server.controllers.data_controller
  /model:
    summary: Controls models
    get:
      tags:
      - Model
      summary: gets model of id
      operationId: get_model
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.model_controller
    put:
      tags:
      - Model
      summary: Adds new model
      operationId: put_model
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.model_controller
    post:
      tags:
      - Model
      summary: Adds new version of model of id
      operationId: post_model
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.model_controller
    delete:
      tags:
      - Model
      summary: Deletes model of id
      operationId: delete_model
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.model_controller
    options:
      tags:
      - Model
      summary: Gets all models
      operationId: options_model
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.model_controller
  /simulation:
    summary: Manages simulations
    get:
      tags:
      - Simulation
      summary: Lists simulations with no id. With id it returns data for simulation
      operationId: get_simulation
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.simulation_controller
    post:
      tags:
      - Simulation
      summary: Creates new simulation. Starts simulation if given id.
      operationId: post_simulation
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.simulation_controller
    options:
      tags:
      - Simulation
      summary: Shows simulation types and options
      operationId: options_simulation
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.simulation_controller
  /scenario:
    summary: Manages scenarios
    get:
      tags:
      - Scenario
      summary: Lists scenarios with no id. With id it returns data for scenario
      operationId: get_scenario
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.scenario_controller
    post:
      tags:
      - Scenario
      summary: Creates new scenario
      operationId: post_scenario
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.scenario_controller
  /bid:
    summary: Controls bidding
    get:
      tags:
      - Bid
      summary: Gets current bid estimate and data with user id.
      operationId: get_bid
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.bid_controller
    post:
      tags:
      - Bid
      summary: Posts bid to server. Returns accepted or denied states.
      operationId: post_bid
      responses:
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.bid_controller
components:
  schemas:
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          example: 400
        message:
          type: string
    Success:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          example: 200
        message:
          type: string
          example: success
      example:
        code: 200
        message: success
    DataSchema:
      required:
      - id
      - fields
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        fields:
          $ref: '#/components/schemas/DataRow'
      example:
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        fields:
          fields:
          - field: field
            datatype: datatype
            value: value
          - field: field
            datatype: datatype
            value: value
    DataRow:
      required:
      - fields
      type: object
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/DataRow_fields'
      example:
        fields:
        - field: field
          datatype: datatype
          value: value
        - field: field
          datatype: datatype
          value: value
    Data:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DataRow'
    DataRow_fields:
      properties:
        field:
          type: string
        datatype:
          type: string
        value:
          type: string
      example:
        field: field
        datatype: datatype
        value: value
  responses:
    ErrorResponse:
      description: Generic error response
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    SuccessResponse:
      description: Successful response
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Success'
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/aaf653e1-0bcd-4c2c-8658-12eb03e15774/oauth2/v2.0/authorize
          scopes:
            User.ReadBasic.All: Ability to read user profile
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_OAuth2
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_OAuth2

